### ISSUE TITLE
BaseException: ('Invalid xpub format', '0x43587cf')

### ISSUE THREAD

**Issue by jidanni** [pooler/electrum-ltc#117]
Now using Master and --testnet
``` 
electrum-ltc-master/electrum-ltc --testnet
Warning: package scrypt not available, using fallback
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/network.py", line 968, in run
    self.run_jobs()    # Synchronizer and Verifier
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/util.py", line 140, in run_jobs
    job.run()
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/synchronizer.py", line 184, in run
    self.wallet.synchronize()
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/wallet.py", line 1675, in synchronize
    self.synchronize_sequence(False)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/wallet.py", line 1670, in synchronize_sequence
    self.create_new_address(for_change)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/wallet.py", line 1653, in create_new_address
    x = self.derive_pubkeys(for_change, n)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/wallet.py", line 1745, in derive_pubkeys
    return self.keystore.derive_pubkey(c, i)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/keystore.py", line 227, in derive_pubkey
    xpub = bip32_public_derivation(self.xpub, "", "/%d"%for_change)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/bitcoin.py", line 1015, in bip32_public_derivation
    xtype, depth, fingerprint, child_number, c, cK = deserialize_xpub(xpub)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/bitcoin.py", line 932, in deserialize_xpub
    return deserialize_xkey(xkey, False)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/bitcoin.py", line 924, in deserialize_xkey
    raise BaseException('Invalid xpub format', hex(header))
BaseException: ('Invalid xpub format', '0x43587cf')
```

**Comment by jidanni** [comment]
The wallet was created with 2.9.3.1. The error was seen in 3.0.3.

**Comment by pooler** [comment]
Electrum 3.0 deprecated the tpub prefix. You should restore the wallet from seed.
https://github.com/spesmilo/electrum/issues/3169#issuecomment-341217798
https://github.com/spesmilo/electrum/issues/3547#issuecomment-352305345
