### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by jidanni** [pooler/electrum-ltc#120]
With fresh Master,
```
$ electrum-ltc-master/electrum-ltc
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/network.py", line 966, in run
    self.wait_on_sockets()
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/network.py", line 948, in wait_on_sockets
    self.process_responses(interface)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/network.py", line 612, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/network.py", line 558, in process_response
    self.on_get_header(interface, response)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/network.py", line 809, in on_get_header
    can_connect = blockchain.can_connect(header)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/blockchain.py", line 101, in can_connect
    if b.can_connect(header):
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/blockchain.py", line 338, in can_connect
    target = self.get_target(height // 2016 - 1)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/blockchain.py", line 299, in get_target
    nActualTimespan = last.get('timestamp') - first.get('timestamp')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by pooler** [comment]
Fixed with commit 082314a6dcc0249e6c3c8d70c20b12114811d8ac.
