### ISSUE TITLE
getprivatekeys shouldn't raise an exception if no such key is in the wallet, just print an error message

### ISSUE THREAD

**Issue by jidanni** [pooler/electrum-ltc#122]
This should just print "no such key in wallet" and return 1 to the
shell, not raise an exception.
```
$ ./electrum-ltc -w $@ --testnet getprivatekeys mw9ABC123_some_not_in_wallet_key
WARNING: ALL your private keys are secret.
Exposing a single private key can compromise your entire wallet!
In particular, DO NOT use 'redeem private key' services proposed by third parties.
Traceback (most recent call last):
  File "./electrum-ltc", line 427, in <module>
    result = run_offline_command(config, config_options)
  File "./electrum-ltc", line 288, in run_offline_command
    result = func(*args, **kwargs)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/commands.py", line 87, in func_wrapper
    return func(*args, **kwargs)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/commands.py", line 281, in getprivatekeys
    return [self.wallet.export_private_key(address, password)[0] for address in domain]
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/commands.py", line 281, in <listcomp>
    return [self.wallet.export_private_key(address, password)[0] for address in domain]
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/wallet.py", line 353, in export_private_key
    index = self.get_address_index(address)
  File "/home/jidanni/com/github/pooler/electrum-ltc-master/lib/wallet.py", line 347, in get_address_index
    raise Exception("Address not found", address)
Exception: ('Address not found', 'm')
```

**Comment by jidanni** [comment]
Also didn't the user enter more than just "m"?
```
Exception: ('Address not found', 'm')
```

**Comment by pooler** [comment]
This is not specific to Electrum-LTC, since Electrum behaves the same way.

Any issue not specific to Litecoin should be reported upstream.
