### ISSUE TITLE
Can't load existing Trezor wallet with 3.0.5.1 on MacOS

### ISSUE THREAD

**Issue by Aragonite** [pooler/electrum-ltc#132]
Traceback (most recent call last):
  File "site-packages/Electrum_LTC-3.0.5.1-py3.6.egg/electrum_ltc/plugins.py", line 151, in get_hardware_support
  File "site-packages/Electrum_LTC-3.0.5.1-py3.6.egg/electrum_ltc/plugins.py", line 179, in get_plugin
  File "site-packages/Electrum_LTC-3.0.5.1-py3.6.egg/electrum_ltc/plugins.py", line 104, in load_plugin
  File "/var/folders/nz/b3272dg17jz6b7z7vcdq_z9m0000gn/T/_MEIrBkAdJ/electrum_ltc_plugins/trezor/trezor.py", line 22, in __init__
    self.types = trezorlib.client.types
AttributeError: module 'trezorlib.client' has no attribute 'types'
[Plugins] cannot load plugin for: trezor

No issues with Trezor & Win 10.
No issues with Keepkey HW wallet on both MacOS and Win 10.

Only Trezor with MacOS seems affected.   Also attempted to created a new Trezor HW wallet file on MacOS, and got the same error.

**Comment by Aragonite** [comment]
No issues with Electrum (Bitcoin) 3.0.5 and Trezor on MacOS.

**Comment by pooler** [comment]
I must have included the wrong version of python-trezor.
Could you please give [this new build](https://electrum-ltc.org/download/electrum-ltc-3.0.5.1-1.dmg) a try?

**Comment by Aragonite** [comment]
It works.

**Comment by pooler** [comment]
Thanks. New build published on the website.
