### ISSUE TITLE
Electrum Server URL Issue with Payment Requests Using Daemon

### ISSUE THREAD

**Issue by raymondcarl** [pooler/electrum-ltc#157]
I have a problem with trying to use the daemon to create a payment request.  I don't think this is a problem related to the Litecoin fork of Electrum, but I wanted to ask @pooler because I think the solution could be easy to figure out to a Python expert and someone who knows their way around the Electrum code base.

I'm using this as a reference to try and generate payment requests for a website using the daemon :  [http://docs.electrum.org/en/latest/merchant.html](http://docs.electrum.org/en/latest/merchant.html)

I was able to open index_url in a web browser from a public server with the IP address but without the SSL related steps and without adding the domain name.  And it was working pretty great.

Today, I got the SSL certificate and domain registered.  Everything works OK until I try this step:
```
./electrum-ltc setconfig url_rewrite "['file:///var/www/','http://my_domain.com/']"  
```
So up until that stage, I'm able to successfully produce the payment request with the default local URL setting.  The instant I add setconfig url rewrite, I get the following error:

```
Invalid call parameters: <Fault -32602: Invalid parameters: replace() takes at most 3 arguments (16 given)>
Traceback (most recent call last):
  File "./electrum-ltc", line 420, in <module>
    result = server.run_cmdline(config_options)
  File "/home/abc/Electrum-LTC-3.0.6.2/packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/home/abc/Electrum-LTC-3.0.6.2/packages/jsonrpclib/jsonrpc.py", line 532, in _request
    check_for_errors(response)
  File "/home/abc/Electrum-LTC-3.0.6.2/packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32602, 'Invalid parameters: replace() takes at most 3 arguments (16 given)')
```
So, I tried to go into the check_for_errors method in the JSON RPC library and see what exactly is going into this error checking function by using the Print() command.  The odd thing is that it seems like a perfectly normal JSON object going into this function (check_for_errors(response)) with 3 elements: {'id': 'fba372df-ffdb-486d-be8f-fc46cef26f6a', 'result': True, 'jsonrpc': '2.0'}.  

This is the JSON object going into the server.run_cmdline({'memo': 'this is a test', 'cmd': 'addrequest', 'amount': '3.14', 'force': False, 'testnet': False, 'cwd': '/home/abc/Electrum-LTC-3.0.6.2', 'password': None, 'portable': False, 'verbose': False}).

I'm fairly new to programming, but it seems to be the case that the JSON RPC call is going OK and the response is actually OK too, but the check_for_errors(response) is not recognizing the response as correct, when it looks to me to be correct.

The jsonrpclib.jsonrpc.ProtocolError: (-32602, 'Invalid parameters: ...   error refers to "Invalid method parameter(s).", but I can't really see anything wrong with it from my point.

I've been playing around with this for 4 hours, and am throwing in the towel on figuring it out myself, but the other ideas I had were that my theory above is wrong and that the SSL certificate (or something related) is actually causing an error somewhere, and what's really happening in that the check_for_errors(response) function is picking up the error message for that, but I'm not able to see it because I'm print in the wrong class and/or method.

**Comment by pooler** [comment]
Probably the same issue as https://github.com/spesmilo/electrum/issues/3833.

**Comment by raymondcarl** [comment]
@pooler  OH MY GOD.........   I cannot believe I spent so many hours trying to figure that out.  Sorry about that.  I searched through every issue I could find in the spesmilo repo and couldn't find anything that hadn't already been fixed.  Thanks a lot for your help and thanks a lot for this fork.  I hope Litepay works out, but I'm getting this working myself just incase it doesn't.  I think Electrum is a great wallet and it's great you forked it for Litecoin.

You can close this issue.
