### ISSUE TITLE
Can't get this to build/run on Ubuntu

### ISSUE THREAD

**Issue by aliensyntax** [pooler/electrum-ltc#186]
I managed to get this client working once before. I set up 2 wallets and added a non-trivial amount of LTC to one of them. Now the LTC is stuck because the client won't actually build/run. The crazy part is that there's no solution/documentation on this issue. I'm a semi-technical user and I don't understand how this problem can be resolved. So, please explain this carefully and without skipping any crucial steps in the process.

Basically, I followed the instructions on the official electrum-ltc.org site. I also tried building from Pooler's dev/master branch. The last thing I tried was to uninstall/re-install all dependencies. Same result each time. The log/traceback states the following in every case:

```
~$ electrum-ltc _(and also ./run_electrum)_
Warning: package scrypt not available; synchronization could be very slow
[SimpleConfig] WARNING: config version (3) is higher than ours (2)
Traceback (most recent call last):
  File "/usr/local/bin/electrum-ltc", line 418, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python3.5/dist-packages/electrum_ltc/daemon.py", line 308, in init_gui
    gui = __import__('electrum_ltc_gui.' + gui_name, fromlist=['electrum_ltc_gui'])
  File "/usr/local/lib/python3.5/dist-packages/electrum_ltc_gui/qt/__init__.py", line 36, in <module>
    from PyQt5.QtGui import *
ImportError: /usr/local/lib/python3.5/dist-packages/PyQt5/QtGui.so: undefined symbol: PySlice_AdjustIndices
```

Seriously, this is undecipherable. I'm not a wizard cryptographer, Python programmer, QT expert, or whatever. I have no idea what this is saying. And I can't find any relevant solution/documentation tied to this output. 

What precise steps should I be following to resolve this problem here? If there's no way to get this client to build/run, how do I actually access the LTC? Can I use the seed to rebuild my wallet with a different client?

Any assistance on this would be appreciated. Thank you.

OS = 4.4.0-130-generic GNU/Linux

**Comment by aliensyntax** [comment]
Solved this by re-installing on a different computer with the latest stable version of Ubuntu (18.04.1 LTS). I have no doubt the dependencies and versioning got screwed up on the first system. The Python toolchain isn't very clear, intuitive, or self-explanatory. Lots of interoperability problems. Anyway, you can close this issue. The software worked great otherwise.
