### ISSUE TITLE
SSL handshake failed on verifying the certificate

### ISSUE THREAD

**Issue by romanornr** [pooler/electrum-ltc#191]
```Warning: package scrypt not available; synchronization could be very slow
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f1efcc37b38>
transport: <_SelectorSocketTransport fd=17 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1045)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f1efcc37b38>
transport: <_SelectorSocketTransport closing fd=17 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1045)
````
electrum wallet keeps hanging too.

**Comment by pooler** [comment]
This does not seem to be specific to Electrum-LTC, as I get the same errors with upstream Electrum.

**Comment by SomberNight** [comment]
Feel free to report this upstream then next time :)

**Comment by pooler** [comment]
@SomberNight Thanks!
