### ISSUE TITLE
ssl 'module' object has no attribute 'PROTOCOL_SSLv3' after distro upgrade

### ISSUE THREAD

**Issue by varogami** [pooler/electrum-ltc#20]
After upgrade my debian to last stable version with python 2.7.9, electrum-tlc not connect to servers and return this error:
```
File "/usr/local/lib/python2.7/dist-packages/electrum_ltc/interface.py", line 381, in start_tcp
ssl_version=ssl.PROTOCOL_SSLv3,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```
I'm not network expert but I tried to change all "ssl.PROTOCOL_SSLv3" to "ssl.PROTOCOL_SSLv23" following old bugs on the electrum:
https://github.com/spesmilo/electrum/commit/c225795793696c5b5d4a9243ebeb129091229ca5

It seems to work but I get another errors:
```
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/electrum_ltc/interface.py", line 587, in run
    self.start_interface()
  File "/usr/local/lib/python2.7/dist-packages/electrum_ltc/interface.py", line 499, in start_interface
    self.start_tcp()
  File "/usr/local/lib/python2.7/dist-packages/electrum_ltc/interface.py", line 335, in start_tcp
    s = ssl.wrap_socket(s, ssl_version=ssl.PROTOCOL_SSLv23, cert_reqs=ssl.CERT_NONE, ca_certs=None)
  File "/usr/lib/python2.7/ssl.py", line 891, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Conexión reinicializada por la máquina remota
```

**Comment by pooler** [comment]
With what version of Electrum-LTC?

**Comment by varogami** [comment]
1.9.8.6

**Comment by varogami** [comment]
On the last start of electrum-ltc I got no errors. I think ssl.PROTOCOL_SSLv3 name have to be changed

**Comment by pooler** [comment]
The patch you mention was applied to our master branch last November, and is present in all 2.x beta releases. By the way, I suggest that you try out release candidate [2.1.1.1](https://litecointalk.org/index.php?topic=18608.msg265384#msg265384), as a lot has changed since 1.9.8.6.

**Comment by varogami** [comment]
ok, thanks
