### ISSUE TITLE
util.py run_with_except_hook network.py  self.wait_on_sockets()

### ISSUE THREAD

**Issue by skazichris** [pooler/electrum-ltc#217]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum_ltc/util.py", line 780, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/dist-packages/electrum_ltc/network.py", line 985, in run
    self.wait_on_sockets()
  File "/usr/local/lib/python3.6/dist-packages/electrum_ltc/network.py", line 967, in wait_on_sockets
    self.process_responses(interface)
  File "/usr/local/lib/python3.6/dist-packages/electrum_ltc/network.py", line 626, in process_responses
    self.process_response(interface, response, callbacks)
  File "/usr/local/lib/python3.6/dist-packages/electrum_ltc/network.py", line 559, in process_response
    if error is None and result > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by pooler** [comment]
What version of Electrum-LTC are you using? How did you install it? When does this happen?

**Comment by skazichris** [comment]
I have used old electrum version before.
I wanted to upgrade.
Latest version cloned from repo via git clone...
Then I used ./run_electrum
Then I pick an address and right click -> Request payment.
Then Bug report messagebox pops up.

niedz., 5 maj 2019, 16:01 użytkownik pooler <notifications@github.com>
napisał:

**Comment by pooler** [comment]
So you are using the latest git master, correct?
Does the same error occur if you create a new wallet?

**Comment by skazichris** [comment]
Yes, latest git master.
Fortunately my wallet is empty. I will recreate and let you know.

niedz., 5 maj 2019, 18:54 użytkownik pooler <notifications@github.com>
napisał:
