### ISSUE TITLE
Conflict of packages when using Electrum and Electum-LTC

### ISSUE THREAD

**Issue by margori** [pooler/electrum-ltc#225]
I'm trying to use Electrum and Electrum-LTC side by side.

I've installed them using 

`pip install [filename].tar.gz`

This is the error I have

`E/i | interface.[****.*************.***:5****] | Exception in wrapper_func: AttributeError("module 'aiorpcx' has no attribute 'Connector'",)
Traceback (most recent call last):
  File "/home/marcelo/.local/lib/python3.6/site-packages/electrum_ltc/util.py", line 888, in wrapper
    return await func(*args, **kwargs)
  File "/home/marcelo/.local/lib/python3.6/site-packages/electrum_ltc/interface.py", line 314, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/marcelo/.local/lib/python3.6/site-packages/electrum_ltc/interface.py", line 329, in run
    ssl_context = await self._get_ssl_context()
  File "/home/marcelo/.local/lib/python3.6/site-packages/electrum_ltc/interface.py", line 297, in _get_ssl_context
    await self._try_saving_ssl_cert_for_first_time(ca_sslc)
  File "/home/marcelo/.local/lib/python3.6/site-packages/electrum_ltc/interface.py", line 254, in _try_saving_ssl_cert_for_first_time
    ca_signed = await self.is_server_ca_signed(ca_ssl_context)
  File "/home/marcelo/.local/lib/python3.6/site-packages/electrum_ltc/interface.py", line 244, in is_server_ca_signed
    await self.open_session(ca_ssl_context, exit_early=True)
  File "/home/marcelo/.local/lib/python3.6/site-packages/electrum_ltc/interface.py", line 420, in open_session
    async with aiorpcx.Connector(NotificationSession,
AttributeError: module 'aiorpcx' has no attribute 'Connector'`

**Comment by pooler** [comment]
The problem seems to be that `aiorpcx` has incompatibilities between minor versions.

You have a few options:

* if on Linux x86-64, you can use the latest Electrum-LTC AppImage;
* or, you can use the latest code from the git repo;
* or, you can wait for the next release.
