### ISSUE TITLE
Startup error on Debian 10 (Wayland)

### ISSUE THREAD

**Issue by mb291** [pooler/electrum-ltc#237]
Hello,

what does rhe following mean:  

`/opt/electrum-ltc/electrum-ltc-3.3.8.1-x86_64.AppImage 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
`

It works mostly nevertheless. Sometimes the gui doesn't come up at all (sporadic).
Anything that can be done about this?

Regards.

**Comment by mb291** [comment]
Follow up:
`/opt/electrum-ltc/electrum-ltc-3.3.8.1-x86_64.AppImage 
^CTraceback (most recent call last):
  File "/tmp/.mount_electr9uUdNF/usr/bin/electrum-ltc", line 358, in <module>
    fd, server = daemon.get_fd_or_server(config)
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/site-packages/electrum_ltc/daemon.py", line 73, in get_fd_or_server
    server = get_server(config)
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/site-packages/electrum_ltc/daemon.py", line 96, in get_server
    server.ping()
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 750, in __call__
    return self.__send(self.__name, kwargs)
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 629, in _request
    response = self._run_request(request)
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 662, in _run_request
    verbose=self.__verbose
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 376, in single_request
    response = connection.getresponse()
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/tmp/.mount_electr9uUdNF/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
`
