### ISSUE TITLE
Cannot import name 'SocksConnector' from 'aiohttp_socks'

### ISSUE THREAD

**Issue by venomone** [pooler/electrum-ltc#243]
Hello,

since a couple of days I'm experiencing the following issue if i do:
```

  echo "Restoring wallet(s) as read-only from Master Public Key"
  {
  electrum-ltc restore $LTC_WALLET_MPK
  }
```

I Install electrum-ltc like so:

pip3 install https://mydomain.com/Electrum-LTC-3.3.8.1.tar.gz#egg=electrum-ltc

-> results in:

> 
> Traceback (most recent call last):
>   File "/usr/local/bin/electrum-ltc", line 82, in <module>
>     from electrum_ltc.logging import get_logger, configure_logging
>   File "/usr/local/lib/python3.8/site-packages/electrum_ltc/__init__.py", line 2, in <module>
>     from .util import format_satoshis
>   File "/usr/local/lib/python3.8/site-packages/electrum_ltc/util.py", line 45, in <module>
>     from aiohttp_socks import SocksConnector, SocksVer
> ImportError: cannot import name 'SocksConnector' from 'aiohttp_socks' (/usr/local/lib/python3.8/site-packages/aiohttp_socks/__init__.py)

Where does this issue comes from?

**Comment by venomone** [comment]
Same issue also goes for electrum-dash wallet

**Comment by venomone** [comment]
v0.5.2 of aiohttp-socks solves the issue, has been release today (GMT)
