### ISSUE TITLE
Does not run with Python 3.12

### ISSUE THREAD

**Issue by alextrezvy** [pooler/electrum-ltc#336]
```
electrum-ltc-4.2.2.1$ ./electrum-env 
Warning: package scrypt not available; synchronization could be very slow
E | daemon.Daemon | GUI raised exception: ModuleNotFoundError("No module named 'distutils'"). shutting down.
E | __main__ | daemon.run_gui errored
Traceback (most recent call last):
  File "/home/user/electrum-ltc-4.2.2.1/./run_electrum", line 426, in handle_cmd
    d.run_gui(config, plugins)
  File "/home/user/electrum-ltc-4.2.2.1/electrum_ltc/daemon.py", line 625, in run_gui
    gui = __import__('electrum_ltc.gui.' + gui_name, fromlist=['electrum_ltc'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/electrum-ltc-4.2.2.1/electrum_ltc/gui/qt/__init__.py", line 65, in <module>
    from .main_window import ElectrumWindow
  File "/home/user/electrum-ltc-4.2.2.1/electrum_ltc/gui/qt/main_window.py", line 101, in <module>
    from .update_checker import UpdateCheck, UpdateCheckThread
  File "/home/user/electrum-ltc-4.2.2.1/electrum_ltc/gui/qt/update_checker.py", line 7, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

**Comment by 1m-dev** [comment]
Got the same issue, did you manage to resolve it?

**Comment by expatjedi** [comment]
I would say that install all required dependencies to run electrum wallet but disutils was removed in Python 3.12 after being deprecated in Python 3.10 so the wallet has to adapt accordingly.
