### ISSUE TITLE
UnboundLocalError: local variable 'tx' referenced before assignment; Electrum-LTC-2.8.3.5

### ISSUE THREAD

**Issue by helmar-gust** [pooler/electrum-ltc#70]
UnboundLocalError: local variable 'tx' referenced before assignment
Traceback (most recent call last):
  File ".../Electrum-LTC-2.8.3.5/gui/qt/fee_slider.py", line 28, in moved
    self.callback(self.dyn, pos, fee_rate)
  File ".../Electrum-LTC-2.8.3.5/gui/qt/main_window.py", line 1028, in fee_cb
    self.spend_max() if self.is_max else self.update_fee()
  File ".../Electrum-LTC-2.8.3.5/gui/qt/main_window.py", line 1114, in spend_max
    self.do_update_fee()
  File ".../Electrum-LTC-2.8.3.5/gui/qt/main_window.py", line 1161, in do_update_fee
    amount = tx.output_value()

while clicking on 'Max' in 'send' in an empty wallet.
Maybe a 'return' missing in ".../Electrum-LTC-2.8.3.5/gui/qt/main_window.py", after line 1153

hlg2000@gmx.de

**Comment by pooler** [comment]
Please upgrade to the latest version and try again.
