### ISSUE TITLE
App will not connect

### ISSUE THREAD

**Issue by dbeckwith** [pooler/electrum-ltc#82]
Every time I open the wallet it says it is not connected, and manually selecting any servers doesn't help.
Tried with version 2.9.3 and 2.9.3.1
The only thing I see in the console is:
```
Warning: ltc_scrypt not available, using fallback
```
But in the past I've seen SSL connect exceptions

**Comment by dbeckwith** [comment]
I reverted back to 2.8.3.5 and it seems to be working, but there's definitely still a problem with 2.9.x

**Comment by pooler** [comment]
What operating system are you using, and how did you install Electrum-LTC?

**Comment by dbeckwith** [comment]
Xubuntu 16.04, I installed by downloading the release and running `contrib/make_packages`, then running the executable in the project root.

**Comment by pooler** [comment]
You should also install the `ltc_scrypt` package, otherwise Electrum-LTC will use the pure Python fallback, which is often too slow to be usable. This is installed automatically by `setup.py`, but if you don't want to install Electrum-LTC you can do this instead:

```
sudo apt-get install python-pip python-dev
sudo pip2 install ltc_scrypt
```

This should make the warning go away, and might fix your issue altogether.

**Comment by dbeckwith** [comment]
When I install `ltc_scrypt` and run it now, I'm back to the SSL errors:
```
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "***/electrum-ltc/lib/interface.py", line 208, in run
    socket = self.get_socket()
  File "***/electrum-ltc/lib/interface.py", line 140, in get_socket
    s = ssl.wrap_socket(s, ssl_version=ssl.PROTOCOL_SSLv23, cert_reqs=ssl.CERT_NONE, ca_certs=None)
  File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer
```

**Comment by dbeckwith** [comment]
(actually now I'm just getting the SSL errors regardless of having `ltc_scrypt` or not)

**Comment by pooler** [comment]
Are you using a proxy? Are you behind some kind of firewall?

Try clearing the data directory (make a backup first) and starting afresh.

**Comment by dbeckwith** [comment]
I am using a VPN, might that affect it? I've tried with a clean data directory.

**Comment by pooler** [comment]
> I am using a VPN, might that affect it?

It might.

**Comment by schors** [comment]
I don't use proxy. I have same effect. Linux Mint 18.2 (based on Ubuntu 16.04 Xenial)

**Comment by twinysam** [comment]
Same issue, on Windows 7, version 3.0.5.1 (official build - windows installer). Added the program exception to the windows Firewall. Tried connecting to servers manually, tried disabling SSL. It just won't connect. Do I need to install Python?

**Comment by pooler** [comment]
@twinysam: no, you don't need to install Python.
