### ISSUE TITLE
Error loading transaction from QR

### ISSUE THREAD

**Issue by estevaocm** [pooler/electrum-ltc#92]
Hello,

Loading transactions from QR codes is failing with the following output to terminal.

This same error used to occur with Electron-Cash, but it was fixed in the recent 3.0 version based on Python 3. The original Electrum is also working well.

Traceback (most recent call last):
  File "/home/user/Downloads/Electrum-LTC-2.9.3.1/gui/qt/main_window.py", line 2056, in read_tx_from_qrcode
    self.show_transaction(tx)
  File "/home/user/Downloads/Electrum-LTC-2.9.3.1/gui/qt/main_window.py", line 737, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/home/user/Downloads/Electrum-LTC-2.9.3.1/gui/qt/transaction_dialog.py", line 45, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/home/user/Downloads/Electrum-LTC-2.9.3.1/gui/qt/transaction_dialog.py", line 61, in __init__
    self.tx.deserialize()
  File "/home/user/Downloads/Electrum-LTC-2.9.3.1/lib/transaction.py", line 582, in deserialize
    d = deserialize(self.raw)
  File "/home/user/Downloads/Electrum-LTC-2.9.3.1/lib/transaction.py", line 455, in deserialize
    d['outputs'] = list(parse_output(vds,i) for i in xrange(n_vout))
  File "/home/user/Downloads/Electrum-LTC-2.9.3.1/lib/transaction.py", line 455, in <genexpr>
    d['outputs'] = list(parse_output(vds,i) for i in xrange(n_vout))
  File "/home/user/Downloads/Electrum-LTC-2.9.3.1/lib/transaction.py", line 433, in parse_output
    d['value'] = vds.read_int64()
  File "/home/user/Downloads/Electrum-LTC-2.9.3.1/lib/transaction.py", line 106, in read_int64
    def read_int64(self): return self._read_num('<q')
  File "/home/user/Downloads/Electrum-LTC-2.9.3.1/lib/transaction.py", line 144, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
struct.error: unpack_from requires a buffer of at least 8 bytes

**Comment by pooler** [comment]
I believe this issue has been fixed in the git repo, so I'm closing the ticket. Feel free to reopen it if that's not the case.
