### ISSUE TITLE
Can't install electrum-ltc from pip2

### ISSUE THREAD

**Issue by Alevale** [pooler/electrum-ltc#95]
Don't know really what I'm doing wrong..

SO: Fresh **Ubuntu 16.04** running on a mac in VBox

Previous commands:
```bash
sudo apt-get install python-qt4 python-pip python-dev
sudo apt-get update
sudo apt-get upgrade
```

Error:
```bash
$ sudo pip2 install https://electrum-ltc.org/download/Electrum-LTC-2.9.3.1.tar.gz
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==8.1.1', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by Alevale** [comment]
This one also doesn't seem to work 
`sudo pip2 install https://electrum-ltc.org/download/Electrum-LTC-2.8.3.5.tar.gz`

**Comment by Alevale** [comment]
Never mind.
After doing 

```bash
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales
```
and selecting all locales it worked.

Maybe it's worth mentioning that you need to select a locale in the setup for the ones like me that are paranoid about security and setup a VM for the ubuntu version 👍
